
name: Auto Hoobly Poster

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  post-listing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium schedule python-dotenv

    - name: Run hoobly poster script
      env:
        HOOBLY_USERNAME: ${{ secrets.HOOBLY_USERNAME }}
        HOOBLY_PASSWORD: ${{ secrets.HOOBLY_PASSWORD }}
      run: |
        python hoobly_poster.py

